'use client';

// import type { Metadata } from 'next';
import { inter } from '@/config/fonts';

import './globals.css';
import { useProductsStore, useCartStore } from '@/store';
import { useEffect } from 'react';

// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	//zustand
	const { fetchProducts } = useProductsStore();
	const { addCartCache } = useCartStore();

	useEffect(() => {
		fetchProducts();
		//get locaal storage
		const cart = localStorage.getItem('cart');
		if (cart) {
			const cartParse = JSON.parse(cart);

			addCartCache(cartParse);

			console.log('cartParse', cartParse);
		}
	}, []);

	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
