'use client';

// import type { Metadata } from 'next';
import { inter } from '@/config/fonts';

import './globals.css';
import { useProductsStore } from '@/store';
import { useEffect } from 'react';

// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	//zustand
	const { loading, error, product, fetchProduct, fetchProducts } =
		useProductsStore();

	useEffect(() => {
		fetchProducts();
	}, []);

	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
